BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBB
 XXXXX  X 
BBBBBBBB
BBBBB BBBBBBBBBBB
 XXXX XXXXXXXXXXXXXXXXXXXX
     XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXX XXXXXXXX
     XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXX
     XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXX XXXX XXXXXXXX
     XXXXXX
 XXXXXX
BBBBBBBB
BBBBB BBBBBBB
 XXXXXXXXX XXXXX
 XXX XXXXXXXXXXXXXXXXXXXXX
     XXXX
         XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
     XXXXX
 XXXXX
 XXXXXXX
     XXXX
         XXXXXXXXXXXXXXXX
         XXXXXXXXX
     XXXXX
     XXXX
         XXXXXXXXXXXXXXXXX
         XXXX XXXXX
     XXXXX
     XXXX
         XXXXXXXXXXXXXX
         XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
     XXXXX
     XXXX
         XXXXXXXXXXXXXXXX
         XXXX
             X
              
         XXXXX
     XXXXX
     XXXX
         XXXXXXXXX XXXXXXXXXXX
         XXXXXXXXXX
     XXXXX
     XXXX
         XXXXXXXXXXXXXXX
         XXXXBB BBBBBBBBBBXXXXBBBBXXXXXXX XXXXXXXBBBBBXXXXX
     XXXXX
 XXXXXXXX
 XXXX XXXXXXXXXXXXXXX
     XXXXXXXXX XXXXXXXXXXX
     XXXXXX XXXXXXXXXXXXXXXXXXX
         XXXXXXX
             XXXX
                 XXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX
             XXXXX
         XXXXXXXX
         XXXXXXX
             BBB BBBB BB BBBBBBBBBBBBBBB
             XXX XXXXXXXXXXBBBBB BBB BBBXX
                 XXXXXXXXX
                 XXX XXXXXXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXXXXX
             XXXXX
             BBBBBB
             XXX XXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXXXXXXXXX
                 XXX XXXXXXXXXXXXXXXXXX
             XXXXX
         XXXXXXXX
     XXXXXXXX
 XXXXXX
BBBBBBBB
