BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB
    
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
        XXXXXXXXX
        XXXX
            XX XXXXXXXX
                
            XXXX
        XXXXX
        XX XXXXXXXXXXXXXXXXX XXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
            
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX
        XXXXXXX        
        FFFFFFFFFF
    XXXXXX
BBBBBBBB
