BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBB
    BB BBBBBBBB
        
    BBBB
        XXXXXXXX
    BBBBB
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXX
            XXX BB BBB BBBBBBBBXXXXXXXXXXXXXXXXBBBBBX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX
            XXXXX
            BBB B BB BBBBBBBBBB
                XXX BB BBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXXXX
                XXXXX
            BBBBBB
        XXXXX
    XXXXXX
    
    XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX
            BB BBBBBBBB
                
            BBBB
                XXXXXXXX
            BBBBB
        XXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX
                        XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                    XXXX
                    XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXX
                XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
BBBBBBBB
