BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBB
    XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXX
        XXXX
            BBB BBBB BB BBBB
                XXXX
                    X 
                    XXXXXXXFFFFFFFFFFFFFXXXXXXX
                XXXXX
            BBBBBB
            BB BBBBBBBBBBB
                XXXX
                    XX XX XXXX
                    XXXXX XXXXXXXXXXXXX XFFFFFFFFFFFFFXXXXXXX
                XXXXX
            BBBBB
        XXXXX
        
        XXXXXXXXX XFFFFFFFFFFFFFXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB
    XXXXXXX
BBBBBBBB
