XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXX XXXXX
        X
        XXX XX X
            XXXXXX XXXXX
        X
        XXXXXXXXXX X
            XXXXXX XXXXX
        X
        XXXX X
            XXXXXXXXXXX XXXXXX
        X
        XXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXX XXX XX X
            XXXXXXX XXX XXXXX XXXXX
        X
        XXX XX X
            XXXXXXXX XXXX
            XXXXXXXXXXX XXXXX
        X
        XX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        XXXXXX X
            XXXXXXXXXXXX XXXXX
        X
        XXXXX X
            XXXXXX XXXXXX
        X
        XXXXXXXX X
            XXXXXX XXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXX XXXXXXXXX
    XXX
        XXXXXXX XXX XXXX
        XXXXX XXXXXXXXXXXXXXXXXX
            FFFFFFF FF FF
        XXXXXXX
    XXXX
    XXXXXXXX XXXXXXX
    XXX
         XXXX
        XXXX
        XXXX
        X 
    XXXX
    XXXXXXXXX XXXXXXXXXXX
    XXXXXXX
        XXXXXXX
            XXXX
                XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXBBBBB BBB BBBXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBBB
            XXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
    XXXXXXXX

    XXXXX XXXXXXXBB BBBBBBBBBBXXXXBBBBXXXXXXXBBBBBXX
        BB BBBBBBBBBBXXXXBBBBXXXXXXX XXXXXXXBBBBB
    XXXXXXX
XXXXXXX
XXXXXXX
