BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXXXXBBBBB BBBBBXX XXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBB B B
            XXXX XXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXX
             XXXXFFFFFFFFFX
            XXX 
            XXXX
            BBBB
            XXXX XXXX XX XXXXXX
            BBBBB
            BBBBBBB
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX
        BBBBB BBBBBBB
        BBBBBBBB
    XXXXXX
XXXXXXX
XXXXXXX
