BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XX XXXXXX XXXXBBBBBBBB

BBBBB BBBBBBB
XXXXXXX XX XXXXXX XXXXXXXXX
XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
XXXXXXX

XXXX XXXXXXX XXX XXXXXXXXX XXXXXXXXXX XXXXXX XXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XX
    XX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX X
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX X
                XXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
            XX
            XXXXXXX X
                XXXXXXX X XXXXXXXXX XXXXXXXXXXXXXX XX
                XXXX X XXXXXXXXX XXXXXX XX
                XXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXX X
            X
        XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX X
                    XX XXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    X

                    XX XXX XXX XXXXX XXXXX XX XXXX XX XXX XXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XX XXXXXX XXX XXXX
                    XXXXXXXXXXXXXX
                XXX
            XX XXXXXXX
        XXX
    XXX
XXXXXXXXX
BBBBBBBB
